### ISSUE TITLE
Page folder not being created

### ISSUE THREAD

**Issue by JanAbe** [rvankoert/loghi#5]
### Problem

I am trying to use loghi to read some old handwritten dutch text but I can't get it to work. 
I followed the README.md to the best of my ability but when I run na-pipeline.sh it doesn't create a page folder. All I see are some errors but I can't seem to understand why it fails. 

I downloaded, as described in the README.md, some files from [surfdrive](https://surfdrive.surf.nl/files/index.php/s/YA8HJuukIUKznSP).

### Config
I changed na-pipeline.sh and added the following as described in the README.md:
`LAYPAMODEL=/home/jdwaal/Workspace/Personal/machine-learning/laypa/general/baseline/config.yaml`

`LAYPAMODELWEIGHTS=/home/jdwaal/Workspace/Personal/machine-learning/laypa/general/baseline/model_best_mIoU.pth`

`HTRLOGHIMODEL=/home/jdwaal/Workspace/Personal/machine-learning/loghi-htr/generic-2023-02-15`

`GPU=-1`

I also added an images folder on the same level as the loghi project. Inside this folder are some downloaded images of dutch handwritten text which I downloaded from [zoekintranscripties.nl](zoekintranscripties.nl), just to see if I could get loghi to work.

### Errors
Below are some errors that might be relevant (I can paste all of the output if you want me to):

```
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
```

```
ValueError: in user code:
    File "/src/loghi-htr/src/data_generator.py", line 95, in load_images  *
        image = tf.io.read_file(image_path[0])
```

```      
Exception in thread "main" java.io.FileNotFoundException: /tmp/tmp.qaVhrR91aG/results.txt (No such file or directory)
```

```
Exception in thread "main" java.nio.file.NoSuchFileException: /home/jdwaal/Workspace/Personal/machine-learning/loghi/images/page
```

I hope my question is clear, if I need to clarify some things, just ask.

Thank you in advance

**Comment by rvankoert** [comment]
It looks like these are the result of an earlier error. Could you run it against a folder with one image in it and post the full output?

**Comment by JanAbe** [comment]
I ran it against a folder containing .jpg image.

This is the full output:

```
jdwaal:~/Workspace/Personal/machine-learning/loghi(main)$ ./na-pipeline.sh /home/jdwaal/Workspace/Personal/machine-learning/images
/tmp/tmp.YioZxEXuM2
starting Laypa baseline detection
docker run --rm -it -u 1000:1000 -m 32000m --shm-size 10240m -v .:. -v /home/jdwaal/Workspace/Personal/machine-learning/images:/home/jdwaal/Workspace/Personal/machine-learning/images -v /home/jdwaal/Workspace/Personal/machine-learning/images:/home/jdwaal/Workspace/Personal/machine-learning/images loghi/docker.laypa:1.3.10 python run.py -c INSERT_FULL_PATH_TO_YAML_HERE -i /home/jdwaal/Workspace/Personal/machine-learning/images -o /home/jdwaal/Workspace/Personal/machine-learning/images --opts MODEL.WEIGHTS  TEST.WEIGHTS INSERT_FULLPATH_TO_PTH_HERE
docker: Error response from daemon: invalid volume specification: '/home/jdwaal/Workspace/Personal/machine-learning/loghi:.': invalid mount config for type "bind": invalid mount path: '.' mount path must be absolute.
See 'docker run --help'.
Exception in thread "main" java.nio.file.NoSuchFileException: /home/jdwaal/Workspace/Personal/machine-learning/images/page
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:432)
	at java.base/java.nio.file.Files.newDirectoryStream(Files.java:472)
	at nl.knaw.huc.di.images.minions.MinionExtractBaselines.main(MinionExtractBaselines.java:391)
starting Loghi HTR
80 [main] ERROR nl.knaw.huc.di.images.minions.MinionCutFromImageBasedOnPageXMLNew - /home/jdwaal/Workspace/Personal/machine-learning/images/page/dutch-text.xml does not exist. Continuing
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

==========
== CUDA ==
==========

CUDA Version 12.2.0

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use the NVIDIA Container Toolkit to start this container with GPU support; see
   https://docs.nvidia.com/datacenter/cloud-native/ .

bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
2024-02-29 09:36:15.698124: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-29 09:36:15.698170: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-29 09:36:15.698253: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-02-29 09:36:15.704901: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-02-29 09:36:16.485540: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/usr/local/lib/python3.10/dist-packages/tensorflow_addons/utils/tfa_eol_msg.py:23: UserWarning: 

TensorFlow Addons (TFA) has ended development and introduction of new features.
TFA has entered a minimal maintenance and release mode until a planned end of life in May 2024.
Please modify downstream libraries to take dependencies from other repositories in our TensorFlow community (e.g. Keras, Keras-CV, and Keras-NLP). 

For more information see: https://github.com/tensorflow/addons/issues/2807 

  warnings.warn(
/usr/local/lib/python3.10/dist-packages/tensorflow_addons/utils/ensure_tf_install.py:53: UserWarning: Tensorflow Addons supports using Python ops for all Tensorflow versions above or equal to 2.11.0 and strictly below 2.14.0 (nightly versions are not supported). 
 The versions of TensorFlow you are currently using is 2.14.0 and is not supported. 
Some things might work, some things might not.
If you were to encounter a bug, do not file an issue.
If you want to make sure you're using a tested and supported configuration, either change the TensorFlow version or the TensorFlow Addons's version. 
You can find the compatibility matrix in TensorFlow Addon's readme:
https://github.com/tensorflow/addons
  warnings.warn(
Matplotlib created a temporary cache directory at /tmp/matplotlib-hva4xg21 because the default path (/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
batch_size > 1, setting use_mask=True
{'gpu': '-1', 'output': '/tmp/tmp.YioZxEXuM2/output/', 'batch_size': 64, 'results_file': '/tmp/tmp.YioZxEXuM2/results.txt', 'config_file_output': '/tmp/tmp.YioZxEXuM2/output/config.json', 'optimizer': 'adam', 'seed': 42, 'channels': 3, 'max_queue_size': 256, 'use_mask': True, 'charlist': '/home/jdwaal/Workspace/Personal/machine-learning/loghi-htr/generic-2023-02-15/charlist.txt', 'output_charlist': None, 'do_train': False, 'learning_rate': 0.0003, 'epochs': 40, 'height': 64, 'width': 65536, 'train_list': None, 'decay_steps': -1, 'decay_rate': 0.99, 'steps_per_epoch': None, 'output_checkpoints': False, 'use_float32': False, 'early_stopping_patience': 20, 'multiply': 1, 'do_validate': False, 'validation_list': None, 'test_list': None, 'training_verbosity_mode': 'auto', 'do_inference': True, 'inference_list': '/tmp/tmp.YioZxEXuM2/lines.txt', 'model': None, 'existing_model': '/home/jdwaal/Workspace/Personal/machine-learning/loghi-htr/generic-2023-02-15', 'model_name': None, 'replace_final_layer': False, 'replace_recurrent_layer': None, 'thaw': False, 'freeze_conv_layers': False, 'freeze_recurrent_layers': False, 'freeze_dense_layers': False, 'augment': False, 'elastic_transform': False, 'random_crop': False, 'random_width': False, 'distort_jpeg': False, 'do_random_shear': False, 'greedy': False, 'beam_width': 1, 'corpus_file': None, 'wbs_smoothing': 0.1, 'do_binarize_otsu': False, 'do_binarize_sauvola': False, 'ignore_lines_unknown_character': False, 'check_missing_files': False, 'normalization_file': None, 'deterministic': False, 'no_auto': False, 'do_blur': False, 'do_invert': False}
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',)
29/02/2024 09:36:17 - INFO - Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',)
Number of devices: 1
using float32
 in charlist, removing
using charlist
length charlist: 454
['\x1b', ' ', '!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '=', '>', '?', '@', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', '\\', ']', '^', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '{', '|', '}', '~', '\x81', '\x83', '\x9d', '\xa0', '£', '¤', '¦', '§', '¨', '©', 'ª', '«', '¬', '\xad', '°', '±', '¶', 'º', '»', '¼', '½', '¾', 'À', 'Á', 'Â', 'Ã', 'Ä', 'Å', 'É', 'Ê', 'Ë', 'Ö', 'Ø', 'Ú', 'ß', 'à', 'á', 'â', 'ã', 'ä', 'å', 'ç', 'è', 'é', 'ê', 'ë', 'ì', 'í', 'ï', 'ñ', 'ò', 'ó', 'ô', 'õ', 'ö', '÷', 'ø', 'ù', 'ú', 'û', 'ü', 'ÿ', 'ā', 'ĉ', 'ċ', 'č', 'ď', 'Đ', 'đ', 'ē', 'ě', 'ĝ', 'ğ', 'ħ', 'ĩ', 'ī', 'ľ', 'ł', 'ň', 'ō', 'ř', 'š', 'ť', 'Ŧ', 'ŧ', 'ũ', 'ū', 'Ż', 'ž', 'ƀ', 'ƒ', 'Ƨ', 'ǂ', 'ǰ', 'Ȇ', 'ȇ', 'ȓ', 'ȝ', 'ȼ', 'ɔ', 'ɫ', 'ʋ', 'ʒ', 'ʳ', 'ˡ', 'ˢ', '˹', '˺', '̃', '̄', '̒', 'ͣ', 'ͩ', '·', 'Α', 'Η', 'κ', 'ϊ', 'ϭ', 'А', 'Б', 'В', 'Г', 'Д', 'Е', 'Ж', 'И', 'К', 'Л', 'М', 'Н', 'О', 'П', 'Р', 'С', 'Т', 'У', 'Ф', 'Х', 'Ц', 'Ч', 'Ш', 'Ъ', 'Ы', 'Э', 'Я', 'а', 'б', 'в', 'г', 'д', 'е', 'ж', 'з', 'и', 'й', 'к', 'л', 'м', 'н', 'о', 'п', 'р', 'с', 'т', 'у', 'ф', 'х', 'ц', 'ч', 'ш', 'щ', 'ъ', 'ы', 'ь', 'ю', 'я', 'ѣ', '֑', '֓', '֖', '֜', '֞', '֣', '֦', '֭', 'ְ', 'ֱ', 'ֲ', 'ֳ', 'ִ', 'ֵ', 'ֶ', 'ַ', 'ָ', 'ֹ', 'ֺ', 'ֻ', 'ּ', 'ֽ', '־', 'ֿ', '׀', 'ׁ', 'ׂ', 'ׄ', 'ׅ', 'ׇ', 'א', 'ב', 'ג', 'ד', 'ה', 'ו', 'ז', 'ח', 'ט', 'י', 'ך', 'כ', 'ל', 'ם', 'מ', 'ן', 'נ', 'ס', 'ע', 'ף', 'פ', 'ץ', 'צ', 'ק', 'ר', 'ש', 'ת', '׳', '״', '؋', '\u061d', '٧', '٨', '۸', 'ᵈ', 'ᵉ', 'ᵗ', 'ᵮ', 'ᶜ', 'ḿ', 'ṁ', 'ṗ', 'ṙ', 'ṽ', 'ẽ', '\u2000', '\u2001', '\u2002', '\u2003', '\u2009', '\u200d', '\u200f', '‒', '–', '—', '―', '‖', '‚', '‛', '„', '‟', '†', '•', '․', '…', '‧', '‰', '′', '″', '‸', '※', '⁁', '⁆', '⁋', '⁓', '⁛', '⁝', '\u206b', '\u206c', '\u206e', 'ⁱ', '₤', '€', '⃞', '℔', '№', '℞', '⅓', '⅔', '⅕', '⅖', '⅗', '⅛', '⅞', '⅟', 'Ⅰ', 'Ⅱ', 'Ⅲ', 'Ⅳ', 'Ⅴ', 'Ⅵ', 'Ⅶ', 'Ⅷ', 'Ⅸ', 'Ⅹ', 'Ⅺ', 'ↄ', '∞', '≠', '┘', '┴', '□', '⛒', '✓', '⸗', 'Ꜣ', 'ꝉ', 'ꝑ', 'Ꝓ', 'ꝓ', 'Ꝕ', 'ꝕ', 'ꝙ', 'ꝝ', 'ꝥ', 'ꝧ', 'ꝫ', 'ꝯ', 'ꝰ', 'ꝶ', 'ꝺ', 'Ꞧ', 'ꞵ', 'ﬨ', 'שׁ', 'שׂ', 'שּׁ', 'אַ', 'אָ', 'בּ', 'גּ', 'דּ', 'וּ', 'כּ', 'פּ', 'קּ', 'תּ', 'וֹ', 'בֿ', 'כֿ', 'פֿ']
WARNING:tensorflow:Mixed precision compatibility check (mixed_float16): WARNING
The dtype policy mixed_float16 may run slowly because this machine does not have a GPU. Only Nvidia GPUs with compute capability of at least 7.0 run quickly with mixed_float16.
If you will use compatible GPU(s) not attached to this host, e.g. by running a multi-worker model, you can ignore this warning. This message will only be logged once
29/02/2024 09:36:17 - WARNING - Mixed precision compatibility check (mixed_float16): WARNING
The dtype policy mixed_float16 may run slowly because this machine does not have a GPU. Only Nvidia GPUs with compute capability of at least 7.0 run quickly with mixed_float16.
If you will use compatible GPU(s) not attached to this host, e.g. by running a multi-worker model, you can ignore this warning. This message will only be logged once
creating generators
found 0 lines suitable for inference
using injected charlist
using mask
64
Traceback (most recent call last):
  File "/src/loghi-htr/src/main.py", line 956, in <module>
    main()
  File "/src/loghi-htr/src/main.py", line 188, in main
    training_generator, evaluation_generator, validation_generator, test_generator, inference_generator, utilsObject, train_batches, val_labels = loader.generators()
  File "/src/loghi-htr/src/data_loader.py", line 158, in generators
    inference_generator = self.init_data_generator(
  File "/src/loghi-htr/src/data_loader.py", line 65, in init_data_generator
    generator = (generator
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 2268, in map
    return map_op._map_v2(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/data/ops/map_op.py", line 40, in _map_v2
    return _ParallelMapDataset(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/data/ops/map_op.py", line 148, in __init__
    self._map_func = structured_function.StructuredFunctionWrapper(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/data/ops/structured_function.py", line 265, in __init__
    self._function = fn_factory()
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py", line 1222, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py", line 1192, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py", line 694, in _initialize
    self._concrete_variable_creation_fn = tracing_compilation.trace_function(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py", line 178, in trace_function
    concrete_function = _maybe_define_function(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py", line 284, in _maybe_define_function
    concrete_function = _create_concrete_function(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py", line 308, in _create_concrete_function
    traced_func_graph = func_graph_module.func_graph_from_py_func(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/func_graph.py", line 1059, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py", line 597, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/data/ops/structured_function.py", line 231, in wrapped_fn
    ret = wrapper_helper(*args)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/data/ops/structured_function.py", line 161, in wrapper_helper
    ret = autograph.tf_convert(self._func, ag_ctx)(*nested_args)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 693, in wrapper
    raise e.ag_error_metadata.to_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 690, in wrapper
    return converted_call(f, args, kwargs, options=options)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 439, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "/tmp/__autograph_generated_filee8qn3boh.py", line 10, in tf__load_images
    image = ag__.converted_call(ag__.ld(tf).io.read_file, (ag__.ld(image_path)[0],), None, fscope)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/ops.py", line 1021, in _create_c_op
    raise ValueError(e.message)
ValueError: in user code:

    File "/src/loghi-htr/src/data_generator.py", line 95, in load_images  *
        image = tf.io.read_file(image_path[0])

    ValueError: Attempting to slice scalar input. for '{{node strided_slice}} = StridedSlice[Index=DT_INT32, T=DT_FLOAT, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1](args_0, strided_slice/stack, strided_slice/stack_1, strided_slice/stack_2)' with input shapes: [], [1], [1], [1] and with computed input tensors: input[3] = <1>.

Exception in thread "main" java.io.FileNotFoundException: /tmp/tmp.YioZxEXuM2/results.txt (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
	at java.base/java.io.FileReader.<init>(FileReader.java:103)
	at nl.knaw.huc.di.images.minions.MinionLoghiHTRMergePageXML.fillDictionary(MinionLoghiHTRMergePageXML.java:336)
	at nl.knaw.huc.di.images.minions.MinionLoghiHTRMergePageXML.main(MinionLoghiHTRMergePageXML.java:247)
recalculating reading order
26 [main] INFO nl.knaw.huc.di.images.minions.MinionRecalculateReadingOrderNew - input_dir: /home/jdwaal/Workspace/Personal/machine-learning/images/page/
Exception in thread "main" java.nio.file.NoSuchFileException: /home/jdwaal/Workspace/Personal/machine-learning/images/page
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:432)
	at java.base/java.nio.file.Files.newDirectoryStream(Files.java:472)
	at nl.knaw.huc.di.images.minions.MinionRecalculateReadingOrderNew.main(MinionRecalculateReadingOrderNew.java:151)
detecting language...
21 [main] INFO nl.knaw.huc.di.images.minions.MinionDetectLanguageOfPageXml - training languages: [English, Italian, French, Latin, German, Dutch]
1022 [pool-1-thread-1] INFO nl.knaw.huc.di.images.minions.MinionDetectLanguageOfPageXml - page: processing file...
1047 [pool-1-thread-1] ERROR nl.knaw.huc.di.images.minions.MinionDetectLanguageOfPageXml - Cannot read page file: /home/jdwaal/Workspace/Personal/machine-learning/images/page
java.nio.file.NoSuchFileException: /home/jdwaal/Workspace/Personal/machine-learning/images/page
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:422)
	at java.base/java.nio.file.Files.readAllBytes(Files.java:3206)
	at java.base/java.nio.file.Files.readString(Files.java:3284)
	at java.base/java.nio.file.Files.readString(Files.java:3243)
	at nl.knaw.huc.di.images.stringtools.StringTools.readFile(StringTools.java:250)
	at nl.knaw.huc.di.images.pagexmlutils.PageUtils.readPageFromFile(PageUtils.java:346)
	at nl.knaw.huc.di.images.minions.MinionDetectLanguageOfPageXml.lambda$main$2(MinionDetectLanguageOfPageXml.java:142)
	at nl.knaw.huc.di.images.minions.MinionDetectLanguageOfPageXml.run(MinionDetectLanguageOfPageXml.java:200)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Exception in thread "pool-1-thread-1" java.lang.NullPointerException
	at nl.knaw.huc.di.images.minions.MinionDetectLanguageOfPageXml.run(MinionDetectLanguageOfPageXml.java:202)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
MinionSplitPageXMLTextLineIntoWords...
Exception in thread "main" java.nio.file.NoSuchFileException: /home/jdwaal/Workspace/Personal/machine-learning/images/page
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:432)
	at java.base/java.nio.file.Files.newDirectoryStream(Files.java:472)
	at nl.knaw.huc.di.images.minions.MinionSplitPageXMLTextLineIntoWords.main(MinionSplitPageXMLTextLineIntoWords.java:93)

```

**Comment by rvankoert** [comment]
It fails due to this line:
docker: Error response from daemon: invalid volume specification: '/home/jdwaal/Workspace/Personal/machine-learning/loghi:.': invalid mount config for type "bind": invalid mount path: '.' mount path must be absolute.
See 'docker run --help'.
Which is really weird. Those paths are typically the same. 

Did you use the na-pipeline.sh from the rvankoert repo?  If so please use the one from:
https://github.com/knaw-huc/loghi 
As that one is better updated and tested

**Comment by JanAbe** [comment]
I cloned the repo from knaw-huc/loghi and ran na-pipeline.sh again, but I still receive this error:

```
docker run --rm -it -u 1000:1000 -m 32000m --shm-size 10240m -v .:. -v /home/jdwaal/Workspace/Personal/machine-learning/images:/home/jdwaal/Workspace/Personal/machine-learning/images -v /home/jdwaal/Workspace/Personal/machine-learning/images:/home/jdwaal/Workspace/Personal/machine-learning/images loghi/docker.laypa:1.3.10 python run.py -c INSERT_FULL_PATH_TO_YAML_HERE -i /home/jdwaal/Workspace/Personal/machine-learning/images -o /home/jdwaal/Workspace/Personal/machine-learning/images --opts MODEL.WEIGHTS  TEST.WEIGHTS INSERT_FULLPATH_TO_PTH_HERE
docker: Error response from daemon: invalid volume specification: '/home/jdwaal/Workspace/Personal/machine-learning/loghi:.': invalid mount config for type "bind": invalid mount path: '.' mount path must be absolute.
```

**Comment by JanAbe** [comment]
What do you mean exactly with "set the path for laypa/loghi-htr again"?

I added the following to my na-pipeline.sh file:

`LAYPAMODEL=/home/jdwaal/Workspace/Personal/machine-learning/laypa/general/baseline/config.yaml`

`LAYPAMODELWEIGHTS=/home/jdwaal/Workspace/Personal/machine-learning/laypa/general/baseline/model_best_mIoU.pth`

`HTRLOGHIMODEL=/home/jdwaal/Workspace/Personal/machine-learning/loghi-htr/generic-2023-02-15`


Do I maybe need to also set this variable?
`LAYPABASELINEMODEL=INSERT_FULL_PATH_TO_YAML_HERE`

**Comment by rvankoert** [comment]
Ah I see it now. Thanks for the suggestion. We changed some of the parameter names but did not update documentation(fixed now). 
Just set 
LAYPABASELINEMODEL=/home/jdwaal/Workspace/Personal/machine-learning/laypa/general/baseline/config.yaml
LAYPABASELINEMODELWEIGHTS=/home/jdwaal/Workspace/Personal/machine-learning/laypa/general/baseline/model_best_mIoU.pth

**Comment by JanAbe** [comment]
Ty it works!

It runs very slowly at the moment because I use the cpu. I also got an nvidia geforce gpu in my laptop but I can't seem to get it to work when setting `GPU=0`.

I followed this nvidia [guide to use nvidia with docker](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#configuring-docker). 

But I get the following error:
RuntimeError: Current CUDA Device does not support bfloat16. Please switch dtype to float16.

(I could paste the full output if wanted)

Do you perhaps know what to do?

Ty in advance

**Comment by stefanklut** [comment]
This indicates that the GPU in your laptop does not support bfloat16, but unlike their recommendation I would suggest running in float32 mode. To run in float32 disable automatic mixed precision (AMP), by doing either `MODEL.AMP_TEST.PRECISION float32` or `MODEL.AMP_TEST.ENABLED False`. This change should be made in the config of Laypa. See https://github.com/knaw-huc/loghi/issues/20 for someone with a similar problem

**Comment by JanAbe** [comment]
I'm sorry I don't know where to place those two properties you mentioned. I can't find a key named `MODEL.AMP_TEST.PRECISION` or `MODEL.AMP_TEST.ENABLED` in `/home/jdwaal/Workspace/Personal/machine-learning/laypa/general/baseline/config.yaml` 

Or am I looking at the wrong place.

**Comment by stefanklut** [comment]
Oh those properties are probably newer than the current public model. You should be able to add the manually to the Laypa config:
```yaml
MODEL:
    AMP_TEST:
        ENABLED: False
```

Or add it to the opts in the na-pipeline.sh at the following line: https://github.com/knaw-huc/loghi/blob/e13d1b8a0eae2f681e37671bc86e18ee0c40e49a/na-pipeline.sh#L104 so that it becomes:
```sh
--opts MODEL.WEIGHTS "" TEST.WEIGHTS $LAYPABASELINEMODELWEIGHTS MODEL.AMP_TEST.ENABLED False | tee -a $tmpdir/log.txt
```

**Comment by JanAbe** [comment]
I added this line:
`--opts MODEL.WEIGHTS "" TEST.WEIGHTS $LAYPABASELINEMODELWEIGHTS MODEL.AMP_TEST.ENABLED False | tee -a $tmpdir/log.txt` to my na-pipeline.sh but I still get the same error.

Do I need to change something else? 
This is my config in na-pipeline.sh:

```
LAYPABASELINEMODEL=/home/jdwaal/Workspace/Personal/machine-learning/laypa/general/baseline/config.yaml 
LAYPABASELINEMODELWEIGHTS=/home/jdwaal/Workspace/Personal/machine-learning/laypa/general/baseline/model_best_mIoU.pth 
HTRLOGHIMODEL=/home/jdwaal/Workspace/Personal/machine-learning/loghi-htr/generic-2023-02-15
```

**Comment by JanAbe** [comment]
Wait it does seem to work now, I copied your na-pipeline.sh and added its content to my file and now it seems to work!

**Comment by JanAbe** [comment]
Ty so much for all you guy's time!
